# Generated by Django 4.2.11 on 2026-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('admin', 'admin'), ('finance', 'finance'), ('sales manager', 'sales manager'), ('sales representative', 'sales representative')], help_text='Role name (admin, finance, sales manager, sales representative)', max_length=50, unique=True, verbose_name='Role Name'),
        ),
    ]
