# Generated by Django 6.1.1 on 2026-09-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(help_text='Role name (e.g. admin, finance, sales manager, sales representative)', max_length=50, unique=True, verbose_name='Role Name'),
        ),
    ]
