# Generated by Django 5.2.16 on 2026-09-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalNegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('requested_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requested_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer_comment', models.TextField(blank=True, null=True)),
                ('sales_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COUNTERED', 'Countered')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portal_negotiations',
            },
        ),
    ]
