# Generated by Django 6.1.1 on 2026-09-05 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tier Name')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Default Discount (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Customer Tier',
                'verbose_name_plural': 'Customer Tiers',
                'db_table': 'customer_tiers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('max_discretionary_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Max Discretionary Discount (%)')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Plan Name')),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20, verbose_name='Billing Frequency')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('billing_address', models.TextField(verbose_name='Billing Address')),
                ('shipping_address', models.TextField(verbose_name='Shipping Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('assigned_sales_rep', models.ForeignKey(blank=True, db_column='assigned_sales_rep_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Sales Rep')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
                ('tier', models.ForeignKey(db_column='tier_id', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='deals.customertier', verbose_name='Customer Tier')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('product_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('SUBSCRIPTION', 'Subscription')], default='ONE_TIME', max_length=20, verbose_name='Product Type')),
                ('unit_of_measure', models.CharField(default='unit', max_length=20, verbose_name='Unit of Measure')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cost Price')),
                ('list_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='List Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='deals.productcategory', verbose_name='Category')),
                ('subscription_plan', models.ForeignKey(blank=True, db_column='subscription_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='deals.subscriptionplan', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_sku', models.CharField(max_length=50, unique=True, verbose_name='Variant SKU')),
                ('attribute_name', models.CharField(max_length=50, verbose_name='Attribute Name')),
                ('attribute_value', models.CharField(max_length=50, verbose_name='Attribute Value')),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Extra Cost')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Extra Price')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='deals.product', verbose_name='Parent Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['variant_sku'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='Quotation Number')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('UNDER_NEGOTIATION', 'Under Negotiation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=30, verbose_name='Status')),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Gross Amount')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Discount Amount')),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Net Amount')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Cost')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margin (%)')),
                ('blended_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Blended Risk Score')),
                ('order_discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Order Discount (%)')),
                ('last_interaction_at', models.DateTimeField(auto_now=True, verbose_name='Last Interaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='deals.customer', verbose_name='Customer')),
                ('sales_rep', models.ForeignKey(db_column='sales_rep_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='Sales Representative')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealHealthAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('STALLED_DEAL', 'Stalled Deal'), ('DISCOUNT_ANOMALY', 'Discount Anomaly'), ('DELIVERY_SLIPPAGE', 'Delivery Slippage'), ('MARGIN_RISK', 'Margin Risk')], max_length=30, verbose_name='Alert Type')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20, verbose_name='Severity')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resolved_by_user', models.ForeignKey(blank=True, db_column='resolved_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_deal_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='health_alerts', to='deals.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Deal Health Alert',
                'verbose_name_plural': 'Deal Health Alerts',
                'db_table': 'deal_health_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blended_risk_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Blended Risk Score')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='deals.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('UPSELL', 'Upsell'), ('CROSS_SELL', 'Cross-sell')], max_length=20, verbose_name='Recommendation Type')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Is Promoted')),
                ('min_margin_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Min Margin Threshold (%)')),
                ('source_product', models.ForeignKey(db_column='source_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_source', to='deals.product', verbose_name='Source Product')),
                ('suggested_product', models.ForeignKey(db_column='suggested_product_id', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_as_target', to='deals.product', verbose_name='Suggested Product')),
            ],
            options={
                'verbose_name': 'Recommendation Rule',
                'verbose_name_plural': 'Recommendation Rules',
                'db_table': 'recommendation_rules',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Price')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cost Price')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Discount Amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tax Amount')),
                ('line_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Line Total')),
                ('margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Margin Amount')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Margin (%)')),
                ('line_risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Line Risk Score')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='deals.product', verbose_name='Product')),
                ('quotation', models.ForeignKey(db_column='quotation_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deals.quotation', verbose_name='Quotation')),
                ('variant', models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='deals.productvariant', verbose_name='Variant')),
                ('subscription_plan', models.ForeignKey(blank=True, db_column='subscription_plan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='deals.subscriptionplan', verbose_name='Subscription Plan')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'quotation_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountTierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_allowed_discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Max Allowed Discount (%)')),
                ('tier', models.ForeignKey(db_column='tier_id', on_delete=django.db.models.deletion.CASCADE, related_name='discount_tier_rules', to='deals.customertier', verbose_name='Customer Tier')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='discount_tier_rules', to='deals.productcategory', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Discount Tier Rule',
                'verbose_name_plural': 'Discount Tier Rules',
                'db_table': 'discount_tier_rules',
                'ordering': ['tier', 'category'],
                'constraints': [models.UniqueConstraint(fields=('tier', 'category'), name='uq_tier_category')],
            },
        ),
    ]
