# Generated by Django 5.2.17 on 2026-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=150)),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('proration_strategy', models.CharField(choices=[('DAILY_PRORATED', 'Daily Prorated'), ('FULL_PERIOD', 'Full Period'), ('NO_PRORATION', 'No Proration')], max_length=20)),
                ('cancellation_terms', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recurring_plans',
            },
        ),
    ]
