# Generated by Django 5.2.17 on 2026-09-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.IntegerField()),
                ('quotation_item_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('MODIFIED', 'Modified'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('proration_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
