# Generated by Django 5.2.17 on 2026-09-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='shipping_cost_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
