# Generated by Django 5.2.17 on 2026-09-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_shipping_cost_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reserved_quantity',
        ),
        migrations.AddField(
            model_name='inventory',
            name='reorder_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product_id', 'variant_id'), name='uq_wh_product_variant'),
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='warehouse_inventory',
        ),
    ]
