# Generated by Django 5.2.17 on 2026-09-05 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfillmentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.IntegerField()),
                ('quotation_item_id', models.IntegerField()),
                ('quantity_fulfilled', models.IntegerField(default=0)),
                ('quantity_backordered', models.IntegerField(default=0)),
                ('split_strategy', models.CharField(choices=[('AUTO_SPLIT', 'Auto Split'), ('MANUAL_OVERRIDE', 'Manual Override')], default='AUTO_SPLIT', max_length=16)),
                ('shipping_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('SHIPPED', 'Shipped'), ('BACKORDERED', 'Backordered'), ('CONSOLIDATED', 'Consolidated')], default='PENDING', max_length=15)),
                ('estimated_shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(db_column='warehouse_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'fulfillment_splits',
            },
        ),
    ]
